include main.mk

ifeq ($(LOGGING),ON)
PARAMS += -DLOGGING=ON
endif

# client-specific build parameters
ifdef SERVER_PORT
CLIENT_PARAMS += -DSERVER_PORT=$(SERVER_PORT)
endif
ifdef SERVER_ADDRESS
CLIENT_PARAMS += -DSERVER_ADDRESS=\"$(SERVER_ADDRESS)\"
endif
ifdef RETRY_COUNT
CLIENT_PARAMS += -DRETRY_COUNT=$(RETRY_COUNT)
endif
ifdef RETRY_INTERVAL
CLIENT_PARAMS += -DRETRY_INTERVAL=$(RETRY_INTERVAL)
endif
